add select color&before, after button
coordinote/Canvas pull request #6
Opened 2017-06-20 07:12 UTC by maturu

要望があった機能を問題なく追加できましたので, ソースの確認をお願いします。

2017-06-20 07:51 UTC, amataku commented on svg-canvas.html
>              <p id="data">0Byte</p>
dataはよく使うのでdatasizeとかの方がいいかも

2017-06-20 07:52 UTC, amataku reviewed
コメントつけた1点のみです

2017-06-20 07:54 UTC, maturu commented on svg-canvas.html
>              <p id="data">0Byte</p>
了解です。

2017-06-20 07:57 UTC, equanz reviewed
ちょいちょい気になる点があったので横から失礼します。

2017-06-20 07:57 UTC, rikyuusima commented on js/draw.js
>  var container = $('#canvas')
DOMを格納する変数は慣例的に `$` をつけて宣言しますがお好きなように…

2017-06-20 07:57 UTC, rikyuusima commented on js/draw.js
> +var array = []
`array` は範囲が広すぎるので `hisotry` とか何かしら分かりやすいほうが良いかと思います

2017-06-20 07:57 UTC, rikyuusima commented on js/draw.js
>  var defaultPathStyle = {
オブジェクトの変更を許可しているので `default` という接頭辞は微妙かと思います  
`pathstyle` とか`property` とかがいいのではないでしょうか

2017-06-20 07:57 UTC, rikyuusima commented on js/draw.js
> +    return this[this.length -1]
どうでもいいけどスペースが気になりますね…

2017-06-20 17:29 UTC, amataku reviewed
変更を確認しました

2017-06-20 17:29 UTC, amataku commented on js/draw.js
> -var container = $('#canvas')
この変数は必要なかったのですか？

2017-06-20 17:44 UTC, maturu commented on js/draw.js
> -var container = $('#canvas')
`$('#canvas').mousedown({. . .}) みたいな感じに置き換えました。

2017-06-20 17:45 UTC, amataku approved these changes

2017-06-20 23:48 UTC, equanz requested changes
定義済みグローバルオブジェクトの取り扱いが今後移植性に問題を生みそうです

2017-06-20 23:48 UTC, rikyuusima commented on js/draw.js
>  String.prototype.size = function() {
グローバルオブジェクトをオーバーライトするのは好ましくないかなと(今後バグの種になりそう)  
別で関数を定義するほうが良いのではないでしょうか

2017-06-20 23:48 UTC, rikyuusima commented on js/draw.js
> +Array.prototype.getLastVal = function() {
グローバルオブジェクトをオーバーライトするのは好ましくない

2017-06-21 09:56 UTC, amataku reviewed
説明をお願いします

2017-06-21 09:56 UTC, amataku commented on js/draw.js
> +
ここから先の関数が無くなっていますがいらなかったのですか？

2017-06-21 09:57 UTC, equanz approved these changes

2017-06-21 13:10 UTC, maturu commented on js/draw.js
> +
htmlのpath の末尾を指定する処理だったのでlengthなどで対応しました！

2017-06-21 13:18 UTC, amataku commented on js/draw.js
> +
了解です

2017-06-21 13:19 UTC, merged